# Generated by Django 4.2.13 on 2024-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pokedex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(default='', max_length=255)),
                ('uploaded', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pokedex',
        ),
    ]
