# Generated by Django 4.2.13 on 2024-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pokedex_identifier_pokedex_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
