# Generated by Django 4.2.13 on 2024-05-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pokemon_latitude_alter_pokemon_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='uploaded',
        ),
    ]
