# Generated by Django 4.2.13 on 2024-05-17 03:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_pokemon_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=[], size=None),
        ),
    ]
