# Generated by Django 4.2.13 on 2024-05-17 03:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_pokemon_remove_userprofile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pokemon',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None),
        ),
    ]
