# Generated by Django 4.2.13 on 2024-05-17 03:31

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pokemon',
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(default='', max_length=255)),
                ('favorited', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
                ('user_profile', models.ForeignKey(default=users.models.UserProfile.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.userprofile')),
            ],
        ),
    ]
