# Generated by Django 4.2.13 on 2024-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pokemon_user_profile_uploadedpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='flavor_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
