# Generated by Django 4.2.13 on 2024-05-17 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pokemon_flavor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
